package com.example.messenger.service;

import com.example.messenger.domain.AppUser;
import com.example.messenger.domain.RefreshToken;
import com.example.messenger.dto.AuthRequest;
import com.example.messenger.dto.AuthResponse;
import com.example.messenger.repository.AppUserRepository;
import com.example.messenger.security.JwtTokenProvider;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.lang.reflect.Field;
import java.time.Instant;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AuthServiceTest {

    private static final Logger log = LoggerFactory.getLogger(AuthServiceTest.class);

    @Mock
    private AppUserRepository appUserRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @Mock
    private JwtTokenProvider jwtTokenProvider;

    @Mock
    private TokenService tokenService;

    @Mock
    private AuthenticationManager authenticationManager;

    @Mock
    private Authentication authentication;

    @InjectMocks
    private AuthService authService;

    private AppUser testUser;

    @BeforeEach
    void setUp() throws Exception {
        log.info("═══════════════════════════════════════════════════════════");
        log.info("Setting up test: {}", getClass().getSimpleName());
        testUser = new AppUser("testuser", "test@example.com", "hashedPassword");
        // Set ID using reflection for testing purposes (ID is normally auto-generated by JPA)
        Field idField = AppUser.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(testUser, 1L);
        log.info("✓ Test user created - ID: {}, Username: {}, Email: {}", 
                testUser.getId(), testUser.getUsername(), testUser.getEmail());
    }

    @AfterEach
    void tearDown() {
        log.info("Test completed: {}", getClass().getSimpleName());
        log.info("═══════════════════════════════════════════════════════════");
    }

    @Test
    void shouldRegisterNewUser() {
        log.info("▶ Starting test: shouldRegisterNewUser");
        
        // Given
        AuthRequest request = new AuthRequest();
        request.setUsernameOrEmail("newuser");
        request.setEmail("new@example.com");
        request.setPassword("password123");
        request.setDisplayName("New User");

        log.info("📋 Test data - Username: {}, Email: {}, DisplayName: {}", 
                request.getUsernameOrEmail(), request.getEmail(), request.getDisplayName());
        log.info("🔧 Setting up mocks...");

        when(appUserRepository.findByEmail(anyString())).thenReturn(Optional.empty());
        log.debug("✓ Mock: findByEmail returns empty");
        when(appUserRepository.findByUsername(anyString())).thenReturn(Optional.empty());
        log.debug("✓ Mock: findByUsername returns empty");
        when(passwordEncoder.encode(anyString())).thenReturn("hashedPassword");
        log.debug("✓ Mock: passwordEncoder.encode returns 'hashedPassword'");
        when(appUserRepository.save(any(AppUser.class))).thenReturn(testUser);
        log.debug("✓ Mock: appUserRepository.save returns testUser");
        when(jwtTokenProvider.generateAccessToken(any())).thenReturn("accessToken");
        log.debug("✓ Mock: jwtTokenProvider.generateAccessToken returns 'accessToken'");
        RefreshToken refreshToken = new RefreshToken(1L, "refreshToken", Instant.now().plusSeconds(3600));
        when(tokenService.createRefreshToken(anyLong())).thenReturn(refreshToken);
        log.debug("✓ Mock: tokenService.createRefreshToken returns refreshToken");

        // When
        log.info("🚀 Executing authService.register()...");
        AuthResponse response = authService.register(request);
        log.info("✅ Service method completed");

        // Then
        log.info("🔍 Validating response...");
        assertNotNull(response, "Response should not be null");
        log.info("✓ Response is not null");
        assertEquals("accessToken", response.getAccessToken(), "Access token should match expected value");
        log.info("✓ Access token validated: {}", response.getAccessToken());
        verify(appUserRepository).save(any(AppUser.class));
        log.info("✓ Verified: appUserRepository.save was called");
        verify(passwordEncoder).encode("password123");
        log.info("✓ Verified: passwordEncoder.encode was called with correct password");
        log.info("✅ Test passed: shouldRegisterNewUser");
    }

    @Test
    void shouldThrowExceptionWhenRegisteringWithDuplicateEmail() {
        log.info("▶ Starting test: shouldThrowExceptionWhenRegisteringWithDuplicateEmail");
        
        // Given
        AuthRequest request = new AuthRequest();
        request.setUsernameOrEmail("newuser");
        request.setEmail("existing@example.com");
        request.setPassword("password123");

        log.info("📋 Test data - Username: {}, Email: {} (duplicate)", 
                request.getUsernameOrEmail(), request.getEmail());
        log.info("🔧 Setting up mocks...");

        when(appUserRepository.findByEmail("existing@example.com")).thenReturn(Optional.of(testUser));
        log.debug("✓ Mock: findByEmail returns existing user");

        // When/Then
        log.info("🚀 Executing authService.register() with duplicate email...");
        log.info("⚠️  Expecting IllegalArgumentException to be thrown");
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, 
                () -> authService.register(request));
        log.info("✅ Exception thrown as expected: {}", exception.getClass().getSimpleName());
        if (exception.getMessage() != null) {
            log.info("📝 Exception message: {}", exception.getMessage());
        }
        verify(appUserRepository, never()).save(any(AppUser.class));
        log.info("✓ Verified: appUserRepository.save was never called");
        log.info("✅ Test passed: shouldThrowExceptionWhenRegisteringWithDuplicateEmail");
    }

    @Test
    void shouldLoginWithValidCredentials() {
        log.info("▶ Starting test: shouldLoginWithValidCredentials");
        
        // Given
        AuthRequest request = new AuthRequest();
        request.setUsernameOrEmail("testuser");
        request.setPassword("password123");

        log.info("📋 Test data - Username: {}", request.getUsernameOrEmail());
        log.info("🔧 Setting up mocks...");

        when(authenticationManager.authenticate(any(UsernamePasswordAuthenticationToken.class)))
                .thenReturn(authentication);
        log.debug("✓ Mock: authenticationManager.authenticate returns authentication");
        when(authentication.getPrincipal()).thenReturn(testUser);
        log.debug("✓ Mock: authentication.getPrincipal returns testUser");
        when(appUserRepository.findByUsername("testuser")).thenReturn(Optional.of(testUser));
        log.debug("✓ Mock: appUserRepository.findByUsername returns testUser");
        when(jwtTokenProvider.generateAccessToken(any())).thenReturn("accessToken");
        log.debug("✓ Mock: jwtTokenProvider.generateAccessToken returns 'accessToken'");
        RefreshToken refreshToken = new RefreshToken(1L, "refreshToken", Instant.now().plusSeconds(3600));
        when(tokenService.createRefreshToken(anyLong())).thenReturn(refreshToken);
        log.debug("✓ Mock: tokenService.createRefreshToken returns refreshToken");

        // When
        log.info("🚀 Executing authService.login()...");
        AuthResponse response = authService.login(request);
        log.info("✅ Service method completed");

        // Then
        log.info("🔍 Validating response...");
        assertNotNull(response, "Response should not be null");
        log.info("✓ Response is not null");
        assertEquals("accessToken", response.getAccessToken(), "Access token should match expected value");
        log.info("✓ Access token validated: {}", response.getAccessToken());
        verify(authenticationManager).authenticate(any(UsernamePasswordAuthenticationToken.class));
        log.info("✓ Verified: authenticationManager.authenticate was called");
        log.info("✅ Test passed: shouldLoginWithValidCredentials");
    }
}
